//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ProjetoIndexacaoDBModel", "FK_MusicaPalavra_Musica", "Musica", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LyricsReader.Musica), "MusicaPalavra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LyricsReader.MusicaPalavra))]
[assembly: EdmRelationshipAttribute("ProjetoIndexacaoDBModel", "FK_MusicaPalavra_Palavra", "Palavra", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LyricsReader.Palavra), "MusicaPalavra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LyricsReader.MusicaPalavra))]
[assembly: EdmRelationshipAttribute("ProjetoIndexacaoDBModel", "Palavra_Bigrama", "Bigrama", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LyricsReader.Bigrama), "Palavra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LyricsReader.Palavra))]

#endregion

namespace LyricsReader
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ProjetoIndexacaoDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ProjetoIndexacaoDBEntities object using the connection string found in the 'ProjetoIndexacaoDBEntities' section of the application configuration file.
        /// </summary>
        public ProjetoIndexacaoDBEntities() : base("name=ProjetoIndexacaoDBEntities", "ProjetoIndexacaoDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProjetoIndexacaoDBEntities object.
        /// </summary>
        public ProjetoIndexacaoDBEntities(string connectionString) : base(connectionString, "ProjetoIndexacaoDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProjetoIndexacaoDBEntities object.
        /// </summary>
        public ProjetoIndexacaoDBEntities(EntityConnection connection) : base(connection, "ProjetoIndexacaoDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Musica> Musicas
        {
            get
            {
                if ((_Musicas == null))
                {
                    _Musicas = base.CreateObjectSet<Musica>("Musicas");
                }
                return _Musicas;
            }
        }
        private ObjectSet<Musica> _Musicas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MusicaPalavra> MusicaPalavras
        {
            get
            {
                if ((_MusicaPalavras == null))
                {
                    _MusicaPalavras = base.CreateObjectSet<MusicaPalavra>("MusicaPalavras");
                }
                return _MusicaPalavras;
            }
        }
        private ObjectSet<MusicaPalavra> _MusicaPalavras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Palavra> Palavras
        {
            get
            {
                if ((_Palavras == null))
                {
                    _Palavras = base.CreateObjectSet<Palavra>("Palavras");
                }
                return _Palavras;
            }
        }
        private ObjectSet<Palavra> _Palavras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bigrama> Bigrama
        {
            get
            {
                if ((_Bigrama == null))
                {
                    _Bigrama = base.CreateObjectSet<Bigrama>("Bigrama");
                }
                return _Bigrama;
            }
        }
        private ObjectSet<Bigrama> _Bigrama;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Musicas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMusicas(Musica musica)
        {
            base.AddObject("Musicas", musica);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MusicaPalavras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMusicaPalavras(MusicaPalavra musicaPalavra)
        {
            base.AddObject("MusicaPalavras", musicaPalavra);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Palavras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPalavras(Palavra palavra)
        {
            base.AddObject("Palavras", palavra);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bigrama EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBigrama(Bigrama bigrama)
        {
            base.AddObject("Bigrama", bigrama);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjetoIndexacaoDBModel", Name="Bigrama")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bigrama : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bigrama object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        /// <param name="extremoAEsquerda">Initial value of the ExtremoAEsquerda property.</param>
        /// <param name="extremoADireita">Initial value of the ExtremoADireita property.</param>
        public static Bigrama CreateBigrama(global::System.Int32 id, global::System.String valor, global::System.Boolean extremoAEsquerda, global::System.Boolean extremoADireita)
        {
            Bigrama bigrama = new Bigrama();
            bigrama.Id = id;
            bigrama.Valor = valor;
            bigrama.ExtremoAEsquerda = extremoAEsquerda;
            bigrama.ExtremoADireita = extremoADireita;
            return bigrama;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.String _Valor;
        partial void OnValorChanging(global::System.String value);
        partial void OnValorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ExtremoAEsquerda
        {
            get
            {
                return _ExtremoAEsquerda;
            }
            set
            {
                OnExtremoAEsquerdaChanging(value);
                ReportPropertyChanging("ExtremoAEsquerda");
                _ExtremoAEsquerda = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExtremoAEsquerda");
                OnExtremoAEsquerdaChanged();
            }
        }
        private global::System.Boolean _ExtremoAEsquerda;
        partial void OnExtremoAEsquerdaChanging(global::System.Boolean value);
        partial void OnExtremoAEsquerdaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ExtremoADireita
        {
            get
            {
                return _ExtremoADireita;
            }
            set
            {
                OnExtremoADireitaChanging(value);
                ReportPropertyChanging("ExtremoADireita");
                _ExtremoADireita = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExtremoADireita");
                OnExtremoADireitaChanged();
            }
        }
        private global::System.Boolean _ExtremoADireita;
        partial void OnExtremoADireitaChanging(global::System.Boolean value);
        partial void OnExtremoADireitaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjetoIndexacaoDBModel", "Palavra_Bigrama", "Palavra")]
        public EntityCollection<Palavra> Palavras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Palavra>("ProjetoIndexacaoDBModel.Palavra_Bigrama", "Palavra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Palavra>("ProjetoIndexacaoDBModel.Palavra_Bigrama", "Palavra", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjetoIndexacaoDBModel", Name="Musica")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Musica : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Musica object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="cantor">Initial value of the Cantor property.</param>
        /// <param name="nomeMusica">Initial value of the NomeMusica property.</param>
        /// <param name="letra">Initial value of the Letra property.</param>
        public static Musica CreateMusica(global::System.Int32 id, global::System.String cantor, global::System.String nomeMusica, global::System.String letra)
        {
            Musica musica = new Musica();
            musica.Id = id;
            musica.Cantor = cantor;
            musica.NomeMusica = nomeMusica;
            musica.Letra = letra;
            return musica;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cantor
        {
            get
            {
                return _Cantor;
            }
            set
            {
                OnCantorChanging(value);
                ReportPropertyChanging("Cantor");
                _Cantor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Cantor");
                OnCantorChanged();
            }
        }
        private global::System.String _Cantor;
        partial void OnCantorChanging(global::System.String value);
        partial void OnCantorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NomeMusica
        {
            get
            {
                return _NomeMusica;
            }
            set
            {
                OnNomeMusicaChanging(value);
                ReportPropertyChanging("NomeMusica");
                _NomeMusica = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NomeMusica");
                OnNomeMusicaChanged();
            }
        }
        private global::System.String _NomeMusica;
        partial void OnNomeMusicaChanging(global::System.String value);
        partial void OnNomeMusicaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Letra
        {
            get
            {
                return _Letra;
            }
            set
            {
                OnLetraChanging(value);
                ReportPropertyChanging("Letra");
                _Letra = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Letra");
                OnLetraChanged();
            }
        }
        private global::System.String _Letra;
        partial void OnLetraChanging(global::System.String value);
        partial void OnLetraChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjetoIndexacaoDBModel", "FK_MusicaPalavra_Musica", "MusicaPalavra")]
        public EntityCollection<MusicaPalavra> MusicaPalavras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MusicaPalavra>("ProjetoIndexacaoDBModel.FK_MusicaPalavra_Musica", "MusicaPalavra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MusicaPalavra>("ProjetoIndexacaoDBModel.FK_MusicaPalavra_Musica", "MusicaPalavra", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjetoIndexacaoDBModel", Name="MusicaPalavra")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MusicaPalavra : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MusicaPalavra object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="indices">Initial value of the Indices property.</param>
        public static MusicaPalavra CreateMusicaPalavra(global::System.Int32 id, global::System.String indices)
        {
            MusicaPalavra musicaPalavra = new MusicaPalavra();
            musicaPalavra.Id = id;
            musicaPalavra.Indices = indices;
            return musicaPalavra;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Indices
        {
            get
            {
                return _Indices;
            }
            set
            {
                OnIndicesChanging(value);
                ReportPropertyChanging("Indices");
                _Indices = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Indices");
                OnIndicesChanged();
            }
        }
        private global::System.String _Indices;
        partial void OnIndicesChanging(global::System.String value);
        partial void OnIndicesChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjetoIndexacaoDBModel", "FK_MusicaPalavra_Musica", "Musica")]
        public Musica Musica
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musica>("ProjetoIndexacaoDBModel.FK_MusicaPalavra_Musica", "Musica").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musica>("ProjetoIndexacaoDBModel.FK_MusicaPalavra_Musica", "Musica").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Musica> MusicaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musica>("ProjetoIndexacaoDBModel.FK_MusicaPalavra_Musica", "Musica");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Musica>("ProjetoIndexacaoDBModel.FK_MusicaPalavra_Musica", "Musica", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjetoIndexacaoDBModel", "FK_MusicaPalavra_Palavra", "Palavra")]
        public Palavra Palavra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Palavra>("ProjetoIndexacaoDBModel.FK_MusicaPalavra_Palavra", "Palavra").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Palavra>("ProjetoIndexacaoDBModel.FK_MusicaPalavra_Palavra", "Palavra").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Palavra> PalavraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Palavra>("ProjetoIndexacaoDBModel.FK_MusicaPalavra_Palavra", "Palavra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Palavra>("ProjetoIndexacaoDBModel.FK_MusicaPalavra_Palavra", "Palavra", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjetoIndexacaoDBModel", Name="Palavra")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Palavra : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Palavra object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static Palavra CreatePalavra(global::System.Int32 id, global::System.String descricao)
        {
            Palavra palavra = new Palavra();
            palavra.Id = id;
            palavra.Descricao = descricao;
            return palavra;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjetoIndexacaoDBModel", "FK_MusicaPalavra_Palavra", "MusicaPalavra")]
        public EntityCollection<MusicaPalavra> MusicaPalavras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MusicaPalavra>("ProjetoIndexacaoDBModel.FK_MusicaPalavra_Palavra", "MusicaPalavra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MusicaPalavra>("ProjetoIndexacaoDBModel.FK_MusicaPalavra_Palavra", "MusicaPalavra", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjetoIndexacaoDBModel", "Palavra_Bigrama", "Bigrama")]
        public EntityCollection<Bigrama> Bigramas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Bigrama>("ProjetoIndexacaoDBModel.Palavra_Bigrama", "Bigrama");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Bigrama>("ProjetoIndexacaoDBModel.Palavra_Bigrama", "Bigrama", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
